import type { PriceList } from '@/lib/types'

export const priceList: PriceList = {
  updatedAt: '2026-02-10',
  effectiveDate: '2026-02-10',
  note: 'Giá niêm yết áp dụng toàn quốc. Giá combo An Nhiên áp dụng khi mua theo thùng/combo định kỳ. Đơn vị: VNĐ.',
  items: [
    // ── ARABICA LINE ───────────────────────────────────────────
    {
      productCode: 'FCD-ARC-NAT-250',
      productName: 'Arabica Cầu Đất Natural 250g',
      unit: 'gói',
      retailPrice: 185000,
      category: 'retail',
    },
    {
      productCode: 'FCD-ARC-NAT-500',
      productName: 'Arabica Cầu Đất Natural 500g',
      unit: 'gói',
      retailPrice: 355000,
      category: 'retail',
    },
    {
      productCode: 'FCD-ARC-WAS-250',
      productName: 'Arabica Cầu Đất Washed 250g',
      unit: 'gói',
      retailPrice: 175000,
      category: 'retail',
    },
    {
      productCode: 'FCD-ARC-WAS-500',
      productName: 'Arabica Cầu Đất Washed 500g',
      unit: 'gói',
      retailPrice: 335000,
      category: 'retail',
    },
    // ── SIGNATURE ─────────────────────────────────────────────
    {
      productCode: 'FCD-SIG-5GU-250',
      productName: 'Signature Blend 5 Gu 250g',
      unit: 'gói',
      retailPrice: 145000,
      comboPrice: 130000,
      comboNote: 'Giá combo khi đặt từ 5 gói',
      category: 'retail',
    },
    {
      productCode: 'FCD-SIG-5GU-500',
      productName: 'Signature Blend 5 Gu 500g',
      unit: 'gói',
      retailPrice: 275000,
      comboPrice: 248000,
      comboNote: 'Giá combo khi đặt từ 3 gói',
      category: 'retail',
    },
    {
      productCode: 'FCD-SIG-5GU-1KG',
      productName: 'Signature Blend 5 Gu 1kg',
      unit: 'hộp',
      retailPrice: 530000,
      comboPrice: 475000,
      comboNote: 'Giá combo An Nhiên',
      category: 'combo',
    },
    // ── EVERYDAY BLEND ────────────────────────────────────────
    {
      productCode: 'FCD-BLD-ANE-250',
      productName: 'An Nhiên Everyday Blend 250g',
      unit: 'gói',
      retailPrice: 115000,
      comboPrice: 104000,
      comboNote: 'Giá khi mua từ 6 gói',
      category: 'retail',
    },
    {
      productCode: 'FCD-BLD-ANE-500',
      productName: 'An Nhiên Everyday Blend 500g',
      unit: 'gói',
      retailPrice: 215000,
      comboPrice: 193000,
      comboNote: 'Giá khi mua từ 3 gói',
      category: 'retail',
    },
    {
      productCode: 'FCD-BLD-ANE-THUNG',
      productName: 'An Nhiên Everyday Blend — Thùng 12×500g',
      unit: 'thùng',
      retailPrice: 2580000,
      comboPrice: 2300000,
      comboNote: 'Freeship nội thành TP.HCM, HN, ĐL',
      category: 'combo',
    },
    // ── ROBUSTA ───────────────────────────────────────────────
    {
      productCode: 'FCD-ROB-BMT-500',
      productName: 'Robusta Buôn Ma Thuột 500g',
      unit: 'gói',
      retailPrice: 125000,
      comboPrice: 112000,
      comboNote: 'Giá khi mua từ 4 gói',
      category: 'retail',
    },
    {
      productCode: 'FCD-ROB-BMT-1KG',
      productName: 'Robusta Buôn Ma Thuột 1kg',
      unit: 'bao',
      retailPrice: 235000,
      comboPrice: 210000,
      comboNote: 'Giá combo',
      category: 'retail',
    },
    // ── ESPRESSO ──────────────────────────────────────────────
    {
      productCode: 'FCD-ESP-DRK-250',
      productName: 'Espresso Dark Roast 250g',
      unit: 'gói',
      retailPrice: 135000,
      comboPrice: 122000,
      comboNote: 'Giá khi mua từ 4 gói',
      category: 'retail',
    },
    {
      productCode: 'FCD-ESP-DRK-500',
      productName: 'Espresso Dark Roast 500g',
      unit: 'gói',
      retailPrice: 255000,
      comboPrice: 230000,
      comboNote: 'Giá combo',
      category: 'retail',
    },
    // ── HIGHLAND BLEND ────────────────────────────────────────
    {
      productCode: 'FCD-NBL-HIG-500',
      productName: 'Nguyên Bản Highland 500g',
      unit: 'gói',
      retailPrice: 155000,
      comboPrice: 140000,
      comboNote: 'Giá khi mua từ 3 gói',
      category: 'retail',
    },
    {
      productCode: 'FCD-NBL-HIG-1KG',
      productName: 'Nguyên Bản Highland 1kg',
      unit: 'bao',
      retailPrice: 295000,
      comboPrice: 265000,
      comboNote: 'Giá combo',
      category: 'retail',
    },
    // ── HỘP QUÀ ──────────────────────────────────────────────
    {
      productCode: 'FCD-GFT-AN3-750',
      productName: 'Hộp Quà An Nhiên — Bộ 3 Vị (3×250g)',
      unit: 'hộp',
      retailPrice: 450000,
      comboPrice: 405000,
      comboNote: 'Giá combo từ 3 hộp',
      category: 'gift',
    },
    // ── BULK ─────────────────────────────────────────────────
    {
      productCode: 'FCD-BLK-BLEND-5KG',
      productName: 'Bulk Blend (nhiều loại) — Bao 5kg',
      unit: 'bao 5kg',
      retailPrice: 950000,
      comboPrice: 850000,
      comboNote: 'Dành cho đại lý, quán cà phê',
      category: 'bulk',
    },
    {
      productCode: 'FCD-BLK-ARC-5KG',
      productName: 'Bulk Arabica Cầu Đất — Bao 5kg',
      unit: 'bao 5kg',
      retailPrice: 1600000,
      comboPrice: 1440000,
      comboNote: 'Dành cho đại lý',
      category: 'bulk',
    },
  ],
}
