import type { Product } from '@/lib/types'

export const products: Product[] = [
  // ── PREMIUM LINE ────────────────────────────────────────────────
  {
    id: 'p001',
    slug: 'arabica-caudat-natural',
    code: 'FCD-ARC-NAT',
    name: 'Arabica Cầu Đất Natural',
    shortName: 'Arabica Natural',
    line: 'premium',
    flavor: {
      category: 'tinh-te',
      bitter: 3,
      sweet: 8,
      sour: 7,
      body: 6,
      aftertaste: 9,
      highlights: ['Đào vàng', 'Mật ong rừng', 'Hoa nhài', 'Cam quýt dịu'],
      suitableFor: ['Người ưa vị chua thanh', 'Filter coffee', 'Cold brew'],
    },
    origin: ['Cầu Đất, Lâm Đồng'],
    ingredients: '100% Arabica Cầu Đất — chế biến Natural (phơi nguyên quả)',
    roastLevel: 'medium-light',
    format: [
      { unit: 'gói', weight: '250g', price: 185000, sku: 'FCD-ARC-NAT-250' },
      { unit: 'gói', weight: '500g', price: 355000, sku: 'FCD-ARC-NAT-500' },
    ],
    description:
      'Arabica Cầu Đất chế biến Natural — phơi nguyên quả dưới nắng cao nguyên 60-90 ngày để lên men tự nhiên, tạo ra profile hương vị ngọt ngào, chua thanh và phức tạp đặc trưng của specialty coffee.',
    notes: ['Đào', 'Mật ong', 'Hoa nhài', 'Cam bergamot'],
    tags: ['arabica', 'natural', 'single-origin', 'specialty', 'filter', 'tinh-te'],
    featured: true,
  },
  {
    id: 'p002',
    slug: 'arabica-caudat-washed',
    code: 'FCD-ARC-WAS',
    name: 'Arabica Cầu Đất Washed',
    shortName: 'Arabica Washed',
    line: 'premium',
    flavor: {
      category: 'tinh-te',
      bitter: 4,
      sweet: 6,
      sour: 8,
      body: 5,
      aftertaste: 8,
      highlights: ['Chanh vàng', 'Hoa trà', 'Vải thiều', 'Táo xanh'],
      suitableFor: ['Người ưa vị chua sáng', 'Pour-over', 'Aeropress'],
    },
    origin: ['Cầu Đất, Lâm Đồng'],
    ingredients: '100% Arabica Cầu Đất — chế biến Washed (rửa nước)',
    roastLevel: 'light',
    format: [
      { unit: 'gói', weight: '250g', price: 175000, sku: 'FCD-ARC-WAS-250' },
      { unit: 'gói', weight: '500g', price: 335000, sku: 'FCD-ARC-WAS-500' },
    ],
    description:
      'Arabica Cầu Đất chế biến Washed — quy trình rửa nước giúp thể hiện rõ terroir vùng trồng với profile chua sáng, trong trẻo và thuần khiết.',
    notes: ['Chanh vàng', 'Hoa trà', 'Vải', 'Táo xanh'],
    tags: ['arabica', 'washed', 'single-origin', 'specialty', 'filter', 'tinh-te'],
    featured: true,
  },
  // ── SIGNATURE LINE ─────────────────────────────────────────────
  {
    id: 'p003',
    slug: 'signature-blend-5gu',
    code: 'FCD-SIG-5GU',
    name: 'FCD Signature Blend 5 Gu',
    shortName: 'Signature Blend',
    line: 'signature',
    flavor: {
      category: 'can-bang',
      bitter: 6,
      sweet: 7,
      sour: 5,
      body: 7,
      aftertaste: 7,
      highlights: ['Chocolate milk', 'Caramel', 'Hạt điều rang', 'Cam nhẹ'],
      suitableFor: ['Uống đen', 'Pha sữa', 'Espresso', 'Cà phê phin truyền thống'],
    },
    origin: ['Cầu Đất, Lâm Đồng', 'Buôn Ma Thuột, Đắk Lắk'],
    ingredients: '70% Arabica Cầu Đất + 30% Robusta Buôn Ma Thuột',
    roastLevel: 'medium',
    format: [
      { unit: 'gói', weight: '250g', price: 145000, priceCombo: 130000, sku: 'FCD-SIG-5GU-250' },
      { unit: 'gói', weight: '500g', price: 275000, priceCombo: 248000, sku: 'FCD-SIG-5GU-500' },
      { unit: 'hộp', weight: '1kg', price: 530000, priceCombo: 475000, sku: 'FCD-SIG-5GU-1KG' },
    ],
    description:
      'Blend đặc trưng của FCD — kết hợp 5 gu vị hài hòa giữa Arabica Cầu Đất và Robusta Buôn Ma Thuột. Phù hợp cho cả uống đen lẫn pha sữa, cà phê phin lẫn espresso machine.',
    notes: ['Chocolate', 'Caramel', 'Hạt điều', 'Cam nhẹ'],
    tags: ['blend', 'signature', 'can-bang', 'phin', 'espresso', 'ban-chay'],
    featured: true,
  },
  // ── CLASSIC LINE ───────────────────────────────────────────────
  {
    id: 'p004',
    slug: 'robusta-buon-ma-thuot',
    code: 'FCD-ROB-BMT',
    name: 'Robusta Buôn Ma Thuột',
    shortName: 'Robusta BMT',
    line: 'classic',
    flavor: {
      category: 'dam-vi',
      bitter: 8,
      sweet: 4,
      sour: 3,
      body: 9,
      aftertaste: 6,
      highlights: ['Đắng đậm', 'Đất ẩm', 'Ca cao thô', 'Khói nhẹ'],
      suitableFor: ['Người ưa đậm vị', 'Pha sữa đặc', 'Cà phê phin truyền thống'],
    },
    origin: ['Buôn Ma Thuột, Đắk Lắk'],
    ingredients: '100% Robusta Buôn Ma Thuột',
    roastLevel: 'dark',
    format: [
      { unit: 'gói', weight: '500g', price: 125000, priceCombo: 112000, sku: 'FCD-ROB-BMT-500' },
      { unit: 'bao', weight: '1kg', price: 235000, priceCombo: 210000, sku: 'FCD-ROB-BMT-1KG' },
    ],
    description:
      'Robusta thuần túy từ thủ phủ cà phê Buôn Ma Thuột — đậm vị, thân dày, crema tốt. Lựa chọn cho những ai ưa cà phê đậm đặc kiểu Việt truyền thống.',
    notes: ['Đắng mạnh', 'Ca cao', 'Đất ẩm', 'Khói nhẹ'],
    tags: ['robusta', 'single-origin', 'dam-vi', 'truyen-thong', 'phin'],
    featured: false,
  },
  {
    id: 'p005',
    slug: 'blend-an-nhien-everyday',
    code: 'FCD-BLD-ANE',
    name: 'An Nhiên Everyday Blend',
    shortName: 'An Nhiên Everyday',
    line: 'blend',
    flavor: {
      category: 'can-bang',
      bitter: 5,
      sweet: 7,
      sour: 4,
      body: 7,
      aftertaste: 7,
      highlights: ['Chocolate sữa', 'Bánh mì nướng', 'Caramel nhẹ'],
      suitableFor: ['Uống hàng ngày', 'Pha sữa', 'Cà phê văn phòng', 'Khách hàng mới'],
    },
    origin: ['Cầu Đất, Lâm Đồng', 'Buôn Ma Thuột, Đắk Lắk'],
    ingredients: '60% Arabica Cầu Đất + 40% Robusta Buôn Ma Thuột',
    roastLevel: 'medium',
    format: [
      { unit: 'gói', weight: '250g', price: 115000, priceCombo: 104000, sku: 'FCD-BLD-ANE-250' },
      { unit: 'gói', weight: '500g', price: 215000, priceCombo: 193000, sku: 'FCD-BLD-ANE-500' },
      { unit: 'thùng', weight: '12x500g', price: 2400000, priceCombo: 2160000, sku: 'FCD-BLD-ANE-THUNG' },
    ],
    description:
      'Blend An Nhiên dành cho uống hàng ngày — cân bằng giữa đậm vị và thơm nhẹ, phù hợp cho mọi khẩu vị và mọi cách pha.',
    notes: ['Chocolate sữa', 'Caramel', 'Bánh mì nướng'],
    tags: ['blend', 'an-nhien', 'can-bang', 'everyday', 'ban-chay', 'combo'],
    featured: true,
  },
  // ── ESPRESSO LINE ──────────────────────────────────────────────
  {
    id: 'p006',
    slug: 'espresso-blend-dark',
    code: 'FCD-ESP-DRK',
    name: 'FCD Espresso Dark Roast',
    shortName: 'Espresso Dark',
    line: 'espresso',
    flavor: {
      category: 'dam-vi',
      bitter: 9,
      sweet: 5,
      sour: 3,
      body: 9,
      aftertaste: 7,
      highlights: ['Dark chocolate', 'Đắng đậm mượt', 'Khói gỗ', 'Crema dày'],
      suitableFor: ['Máy espresso', 'Americano', 'Latte', 'Cappuccino'],
    },
    origin: ['Cầu Đất, Lâm Đồng', 'Buôn Ma Thuột, Đắk Lắk'],
    ingredients: '40% Arabica Cầu Đất + 60% Robusta Buôn Ma Thuột',
    roastLevel: 'dark',
    format: [
      { unit: 'gói', weight: '250g', price: 135000, priceCombo: 122000, sku: 'FCD-ESP-DRK-250' },
      { unit: 'gói', weight: '500g', price: 255000, priceCombo: 230000, sku: 'FCD-ESP-DRK-500' },
    ],
    description:
      'Rang đậm đặc trưng cho espresso — crema dày, đắng mượt, thân vị nặng. Tối ưu cho máy espresso bán tự động và tự động.',
    notes: ['Dark chocolate', 'Khói gỗ', 'Caramel cháy'],
    tags: ['espresso', 'dark-roast', 'dam-vi', 'may-espresso'],
    featured: false,
  },
  // ── GIFT LINE ──────────────────────────────────────────────────
  {
    id: 'p007',
    slug: 'hop-qua-an-nhien-3vi',
    code: 'FCD-GFT-AN3',
    name: 'Hộp Quà An Nhiên — Bộ 3 Vị',
    shortName: 'Hộp Quà 3 Vị',
    line: 'gift',
    flavor: {
      category: 'can-bang',
      bitter: 6,
      sweet: 7,
      sour: 5,
      body: 7,
      aftertaste: 7,
      highlights: ['Đa dạng 3 gu vị', 'Arabica & Robusta', 'Natural & Washed'],
      suitableFor: ['Quà tặng cá nhân', 'Quà tặng doanh nghiệp', 'Dùng thử nhiều gu'],
    },
    origin: ['Cầu Đất, Lâm Đồng', 'Buôn Ma Thuột, Đắk Lắk'],
    ingredients: 'Arabica Natural 250g + Arabica Washed 250g + Signature Blend 250g',
    roastLevel: 'medium',
    format: [
      { unit: 'hộp', weight: '3×250g', price: 450000, priceCombo: 405000, sku: 'FCD-GFT-AN3-750' },
    ],
    description:
      'Bộ quà cao cấp gồm 3 loại cà phê đặc sản FCD trong hộp thiết kế premium — món quà ý nghĩa cho người yêu cà phê hoặc dịp tặng đối tác doanh nghiệp.',
    notes: ['Combo 3 vị', 'Hộp thiết kế đẹp', 'Phù hợp làm quà'],
    tags: ['gift', 'qua-tang', 'combo', 'doanh-nghiep', 'an-nhien'],
    featured: true,
  },
  // ── BLEND NGUYEN BAN ───────────────────────────────────────────
  {
    id: 'p008',
    slug: 'nguyen-ban-highland-blend',
    code: 'FCD-NBL-HIG',
    name: 'FCD Nguyên Bản Highland',
    shortName: 'Nguyên Bản Highland',
    line: 'classic',
    flavor: {
      category: 'nguyen-ban',
      bitter: 6,
      sweet: 6,
      sour: 5,
      body: 8,
      aftertaste: 6,
      highlights: ['Vị đất cao nguyên', 'Ổi xanh', 'Trái cây khô', 'Cacao nhẹ'],
      suitableFor: ['Người ưa vị truyền thống', 'Cà phê sáng sớm', 'Uống nóng với sữa'],
    },
    origin: ['Cầu Đất, Lâm Đồng', 'Buôn Ma Thuột, Đắk Lắk'],
    ingredients: '50% Arabica Cầu Đất + 50% Robusta Buôn Ma Thuột',
    roastLevel: 'medium-dark',
    format: [
      { unit: 'gói', weight: '500g', price: 155000, priceCombo: 140000, sku: 'FCD-NBL-HIG-500' },
      { unit: 'bao', weight: '1kg', price: 295000, priceCombo: 265000, sku: 'FCD-NBL-HIG-1KG' },
    ],
    description:
      'Blend "nguyên bản" mang vị cà phê cao nguyên Việt — không cầu kỳ, không áp đặt, chỉ đơn giản là cà phê ngon đúng nghĩa mỗi sáng.',
    notes: ['Đất cao nguyên', 'Ổi xanh', 'Cacao'],
    tags: ['blend', 'nguyen-ban', 'truyen-thong', 'highland'],
    featured: false,
  },
]
